#!/usr/bin/env python3
"""
Publishes the calibrated base->d435_link static TF.
Reads from config/camera_base_tf.yaml (generated by collector.py).
Keep this running so Foxglove can verify depth projection.
"""

import sys
import yaml
from pathlib import Path

import rclpy
from rclpy.node import Node
from ament_index_python.packages import get_package_share_directory
from tf2_ros import StaticTransformBroadcaster
from geometry_msgs.msg import TransformStamped


class CalibrationTFPublisher(Node):
    def __init__(self):
        super().__init__('calibration_tf_publisher')

        pkg_share = Path(get_package_share_directory('hand_eye_calibration'))
        config_path = pkg_share / 'config' / 'camera_base_tf.yaml'

        if not config_path.exists():
            self.get_logger().error(
                f'Calibration file not found: {config_path}\n'
                'Run collect.launch.py first to generate calibration.')
            sys.exit(1)

        with open(config_path) as f:
            cfg = yaml.safe_load(f)

        self.broadcaster = StaticTransformBroadcaster(self)

        tf_msg = TransformStamped()
        tf_msg.header.stamp = self.get_clock().now().to_msg()
        tf_msg.header.frame_id = cfg['frame_id']
        tf_msg.child_frame_id = cfg['child_frame_id']

        tf_msg.transform.translation.x = cfg['translation']['x']
        tf_msg.transform.translation.y = cfg['translation']['y']
        tf_msg.transform.translation.z = cfg['translation']['z']
        tf_msg.transform.rotation.x = cfg['rotation']['x']
        tf_msg.transform.rotation.y = cfg['rotation']['y']
        tf_msg.transform.rotation.z = cfg['rotation']['z']
        tf_msg.transform.rotation.w = cfg['rotation']['w']

        self.broadcaster.sendTransform(tf_msg)

        self.get_logger().info(
            f'Published static TF: {cfg["frame_id"]} -> {cfg["child_frame_id"]}\n'
            f'  Translation: ({cfg["translation"]["x"]:.4f}, '
            f'{cfg["translation"]["y"]:.4f}, {cfg["translation"]["z"]:.4f})\n'
            f'  Rotation (xyzw): ({cfg["rotation"]["x"]:.4f}, '
            f'{cfg["rotation"]["y"]:.4f}, {cfg["rotation"]["z"]:.4f}, '
            f'{cfg["rotation"]["w"]:.4f})'
        )
        self.get_logger().info(
            'TF published. Connect Foxglove to verify depth projection.\n'
            'In Foxglove 3D panel, set "Follow frame" to "base" and\n'
            'enable depth/point cloud visualization.'
        )


def main(args=None):
    rclpy.init(args=args)
    node = CalibrationTFPublisher()
    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        node.destroy_node()
        if rclpy.ok():
            rclpy.shutdown()


if __name__ == '__main__':
    main()
